name: GitLabInMenubar
options:
  bundleIdPrefix: com.basarozcan
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.3"
  minimumXcodeGenVersion: "2.40"

targets:
  GitLabInMenubar:
    type: application
    platform: macOS
    sources:
      - GitLabInMenubar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basarozcan.GitLabInMenubar
        PRODUCT_NAME: GitLabInMenubar
        MARKETING_VERSION: "1.0.2"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: GitLabInMenubar/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: GitLabInMenubar/GitLabInMenubar.entitlements
        ENABLE_HARDENED_RUNTIME: true
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: GitLabInMenubar/GitLabInMenubar.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true

  GitLabInMenubarTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - GitLabInMenubarTests
    dependencies:
      - target: GitLabInMenubar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basarozcan.GitLabInMenubarTests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true
