name: GitLabMRStatus
options:
  bundleIdPrefix: com.basarozcan
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.3"
  minimumXcodeGenVersion: "2.40"

targets:
  GitLabMRStatus:
    type: application
    platform: macOS
    sources:
      - GitLabMRStatus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basarozcan.GitLabMRStatus
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        INFOPLIST_FILE: GitLabMRStatus/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: GitLabMRStatus/GitLabMRStatus.entitlements
        ENABLE_HARDENED_RUNTIME: true
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: GitLabMRStatus/GitLabMRStatus.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true

  GitLabMRStatusTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - GitLabMRStatusTests
    dependencies:
      - target: GitLabMRStatus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.basarozcan.GitLabMRStatusTests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: true
